//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dll_seguridad.Recursos_localizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dll_seguridad.Recursos_localizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        public static string ButtonLabel1 {
            get {
                return ResourceManager.GetString("ButtonLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string ButtonLabel2 {
            get {
                return ResourceManager.GetString("ButtonLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaCreacionModulo.
        /// </summary>
        public static string Label10 {
            get {
                return ResourceManager.GetString("Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaModificacionModulo.
        /// </summary>
        public static string Label11 {
            get {
                return ResourceManager.GetString("Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulo.
        /// </summary>
        public static string Label12 {
            get {
                return ResourceManager.GetString("Label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreDLL.
        /// </summary>
        public static string Label13 {
            get {
                return ResourceManager.GetString("Label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstadoDLL.
        /// </summary>
        public static string Label14 {
            get {
                return ResourceManager.GetString("Label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreModulo.
        /// </summary>
        public static string Label15 {
            get {
                return ResourceManager.GetString("Label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaCreacionModulo.
        /// </summary>
        public static string Label16 {
            get {
                return ResourceManager.GetString("Label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaModificacionModulo.
        /// </summary>
        public static string Label17 {
            get {
                return ResourceManager.GetString("Label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodigoPerfil.
        /// </summary>
        public static string Label18 {
            get {
                return ResourceManager.GetString("Label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstadoPerfil.
        /// </summary>
        public static string Label19 {
            get {
                return ResourceManager.GetString("Label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hospitalario.
        /// </summary>
        public static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombrePerfil.
        /// </summary>
        public static string Label20 {
            get {
                return ResourceManager.GetString("Label20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaCreacionPerfil.
        /// </summary>
        public static string Label21 {
            get {
                return ResourceManager.GetString("Label21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaModificacionPerfil.
        /// </summary>
        public static string Label22 {
            get {
                return ResourceManager.GetString("Label22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roll.
        /// </summary>
        public static string Label23 {
            get {
                return ResourceManager.GetString("Label23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreRoll.
        /// </summary>
        public static string Label24 {
            get {
                return ResourceManager.GetString("Label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstadoRoll.
        /// </summary>
        public static string Label25 {
            get {
                return ResourceManager.GetString("Label25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaCreacionRoll.
        /// </summary>
        public static string Label26 {
            get {
                return ResourceManager.GetString("Label26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaModificacionRoll.
        /// </summary>
        public static string Label27 {
            get {
                return ResourceManager.GetString("Label27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DescripcionRoll.
        /// </summary>
        public static string Label28 {
            get {
                return ResourceManager.GetString("Label28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdSubMod.
        /// </summary>
        public static string Label29 {
            get {
                return ResourceManager.GetString("Label29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Label3 {
            get {
                return ResourceManager.GetString("Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdMod.
        /// </summary>
        public static string Label30 {
            get {
                return ResourceManager.GetString("Label30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstadoSubMod.
        /// </summary>
        public static string Label31 {
            get {
                return ResourceManager.GetString("Label31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreSubMod.
        /// </summary>
        public static string Label32 {
            get {
                return ResourceManager.GetString("Label32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreFormulario.
        /// </summary>
        public static string Label33 {
            get {
                return ResourceManager.GetString("Label33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaCreacionFormulario.
        /// </summary>
        public static string Label34 {
            get {
                return ResourceManager.GetString("Label34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaModificacionFormulario.
        /// </summary>
        public static string Label35 {
            get {
                return ResourceManager.GetString("Label35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdUsuario.
        /// </summary>
        public static string Label36 {
            get {
                return ResourceManager.GetString("Label36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodigoPerfilUsuario.
        /// </summary>
        public static string Label37 {
            get {
                return ResourceManager.GetString("Label37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RollUsuario.
        /// </summary>
        public static string Label38 {
            get {
                return ResourceManager.GetString("Label38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstadoUsuario.
        /// </summary>
        public static string Label39 {
            get {
                return ResourceManager.GetString("Label39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreUsuario.
        /// </summary>
        public static string Label40 {
            get {
                return ResourceManager.GetString("Label40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DireccionUsuario.
        /// </summary>
        public static string Label41 {
            get {
                return ResourceManager.GetString("Label41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PrimerApellidoUsuario.
        /// </summary>
        public static string Label42 {
            get {
                return ResourceManager.GetString("Label42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AliasUsuario.
        /// </summary>
        public static string Label43 {
            get {
                return ResourceManager.GetString("Label43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SegundoApellidoUsuario.
        /// </summary>
        public static string Label44 {
            get {
                return ResourceManager.GetString("Label44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ContraseñaUsuario.
        /// </summary>
        public static string Label45 {
            get {
                return ResourceManager.GetString("Label45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaCreacionUsuario.
        /// </summary>
        public static string Label46 {
            get {
                return ResourceManager.GetString("Label46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaModifUsuario.
        /// </summary>
        public static string Label47 {
            get {
                return ResourceManager.GetString("Label47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        public static string Label5 {
            get {
                return ResourceManager.GetString("Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodigoDetalleModulo.
        /// </summary>
        public static string Label6 {
            get {
                return ResourceManager.GetString("Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodigoModulo.
        /// </summary>
        public static string Label7 {
            get {
                return ResourceManager.GetString("Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodigoPerfil.
        /// </summary>
        public static string Label8 {
            get {
                return ResourceManager.GetString("Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstadoDetalleModulo.
        /// </summary>
        public static string Label9 {
            get {
                return ResourceManager.GetString("Label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesion.
        /// </summary>
        public static string WindowTitle1 {
            get {
                return ResourceManager.GetString("WindowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Modulo.
        /// </summary>
        public static string WindowTitle2 {
            get {
                return ResourceManager.GetString("WindowTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulo.
        /// </summary>
        public static string WindowTitle3 {
            get {
                return ResourceManager.GetString("WindowTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfiles.
        /// </summary>
        public static string WindowTitle4 {
            get {
                return ResourceManager.GetString("WindowTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string WindowTitle5 {
            get {
                return ResourceManager.GetString("WindowTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubModulo.
        /// </summary>
        public static string WindowTitle6 {
            get {
                return ResourceManager.GetString("WindowTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string WindowTitle7 {
            get {
                return ResourceManager.GetString("WindowTitle7", resourceCulture);
            }
        }
    }
}
