//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dll_idioma.idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cambiolabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cambiolabel() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dll_idioma.idiomas.cambiolabel", typeof(cambiolabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Apellido.
        /// </summary>
        internal static string lbl1apellido {
            get {
                return ResourceManager.GetString("lbl1apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Apellido.
        /// </summary>
        internal static string lbl2apellido {
            get {
                return ResourceManager.GetString("lbl2apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias.
        /// </summary>
        internal static string lblalias {
            get {
                return ResourceManager.GetString("lblalias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Módulo.
        /// </summary>
        internal static string lblcodmod {
            get {
                return ResourceManager.GetString("lblcodmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código perfil.
        /// </summary>
        internal static string lblcodperfil {
            get {
                return ResourceManager.GetString("lblcodperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código sub módulo.
        /// </summary>
        internal static string lblcodsubmod {
            get {
                return ResourceManager.GetString("lblcodsubmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código usuario.
        /// </summary>
        internal static string lblcodusuario {
            get {
                return ResourceManager.GetString("lblcodusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblcontraseña {
            get {
                return ResourceManager.GetString("lblcontraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string lbldireccion {
            get {
                return ResourceManager.GetString("lbldireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string lblestado {
            get {
                return ResourceManager.GetString("lblestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha creación.
        /// </summary>
        internal static string lblfechcreacion {
            get {
                return ResourceManager.GetString("lblfechcreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha modificación.
        /// </summary>
        internal static string lblfechmodificacion {
            get {
                return ResourceManager.GetString("lblfechmodificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string lbliddetmod {
            get {
                return ResourceManager.GetString("lbliddetmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        internal static string lblmoneda {
            get {
                return ResourceManager.GetString("lblmoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre perfil.
        /// </summary>
        internal static string lblnombreperfil {
            get {
                return ResourceManager.GetString("lblnombreperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblnombreusuario {
            get {
                return ResourceManager.GetString("lblnombreusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Fomulario.
        /// </summary>
        internal static string lblnombrewf {
            get {
                return ResourceManager.GetString("lblnombrewf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre DLL.
        /// </summary>
        internal static string lblnomdll {
            get {
                return ResourceManager.GetString("lblnomdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Módulo.
        /// </summary>
        internal static string lblnommodulo {
            get {
                return ResourceManager.GetString("lblnommodulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre sub módulo.
        /// </summary>
        internal static string lblnomsubmod {
            get {
                return ResourceManager.GetString("lblnomsubmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblusuario {
            get {
                return ResourceManager.GetString("lblusuario", resourceCulture);
            }
        }
    }
}
